modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''
config="${mod_id}.mixins.json"

[[dependencies.neoforge]]
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.minecraft]]
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    type="required"
    versionRange="[6.0,)"
    ordering="AFTER"
    side="BOTH"